<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmployeeStatus extends BaseEmployeeStatus
{
    public function __toString() {
        return $this->name;
    }  
}