<?php
/**
 * Subunit class file
 */

/**
 * Subunit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class Subunit extends PluginSubunit
{
}
