<?php

/**
 * PluginEmploymentStatus class file
 */

/**
 * PluginEmploymentStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginEmploymentStatus extends BaseEmploymentStatus
{

}