<?php

/**
 * PluginJobCategory class file
 */

/**
 * PluginJobCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginJobCategory extends BaseJobCategory
{

}