<?php

/**
 * PluginWorkShift class file
 */

/**
 * PluginWorkShift
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginWorkShift extends BaseWorkShift
{
	const	DEFAULT_WORK_SHIFT_LENGTH = 8;
}