<?php

/**
 * PluginDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDepartment');
    }
}