<?php

/**
 * PluginJobTitleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJobTitleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJobTitleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJobTitle');
    }
}