<?php

/**
 * AvailableDisplayFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvailableDisplayFieldTable extends PluginAvailableDisplayFieldTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvailableDisplayFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AvailableDisplayField');
    }
}