<?php

/**
 * PluginEmployeeLicenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmployeeLicenseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmployeeLicenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmployeeLicense');
    }
}