<?php

/**
 * BaseJobSpecificationAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $jobTitleId
 * @property string $fileName
 * @property string $fileType
 * @property integer $fileSize
 * @property blob $fileContent
 * @property JobTitle $JobTitle
 * 
 * @method integer                    getId()          Returns the current record's "id" value
 * @method integer                    getJobTitleId()  Returns the current record's "jobTitleId" value
 * @method string                     getFileName()    Returns the current record's "fileName" value
 * @method string                     getFileType()    Returns the current record's "fileType" value
 * @method integer                    getFileSize()    Returns the current record's "fileSize" value
 * @method blob                       getFileContent() Returns the current record's "fileContent" value
 * @method JobTitle                   getJobTitle()    Returns the current record's "JobTitle" value
 * @method JobSpecificationAttachment setId()          Sets the current record's "id" value
 * @method JobSpecificationAttachment setJobTitleId()  Sets the current record's "jobTitleId" value
 * @method JobSpecificationAttachment setFileName()    Sets the current record's "fileName" value
 * @method JobSpecificationAttachment setFileType()    Sets the current record's "fileType" value
 * @method JobSpecificationAttachment setFileSize()    Sets the current record's "fileSize" value
 * @method JobSpecificationAttachment setFileContent() Sets the current record's "fileContent" value
 * @method JobSpecificationAttachment setJobTitle()    Sets the current record's "JobTitle" value
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobSpecificationAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_job_specification_attachment');
        $this->hasColumn('id', 'integer', 13, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 13,
             ));
        $this->hasColumn('job_title_id as jobTitleId', 'integer', 13, array(
             'type' => 'integer',
             'length' => 13,
             ));
        $this->hasColumn('file_name as fileName', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file_type as fileType', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file_size as fileSize', 'integer', 30, array(
             'type' => 'integer',
             'length' => 30,
             ));
        $this->hasColumn('file_content as fileContent', 'blob', 2147483647, array(
             'type' => 'blob',
             'length' => 2147483647,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JobTitle', array(
             'local' => 'jobTitleId',
             'foreign' => 'id'));
    }
}