<?php

/**
 * BaseLeaveEntitlementAdjustment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $adjustment_id
 * @property integer $entitlement_id
 * @property decimal $length_days
 * 
 * @method integer                    getId()             Returns the current record's "id" value
 * @method integer                    getAdjustmentId()   Returns the current record's "adjustment_id" value
 * @method integer                    getEntitlementId()  Returns the current record's "entitlement_id" value
 * @method decimal                    getLengthDays()     Returns the current record's "length_days" value
 * @method LeaveEntitlementAdjustment setId()             Sets the current record's "id" value
 * @method LeaveEntitlementAdjustment setAdjustmentId()   Sets the current record's "adjustment_id" value
 * @method LeaveEntitlementAdjustment setEntitlementId()  Sets the current record's "entitlement_id" value
 * @method LeaveEntitlementAdjustment setLengthDays()     Sets the current record's "length_days" value
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveEntitlementAdjustment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_entitlement_adjustment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('adjustment_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entitlement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('length_days', 'decimal', 4, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}