<?php

/**
 * PluginReportingMethodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginReportingMethodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginReportingMethodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginReportingMethod');
    }
}