<?php

/**
 * I18NSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class I18NSourceTable extends PluginI18NSourceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return I18NSourceTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('I18NSource');
    }
}
