<?php

/**
 * I18NLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class I18NLanguageTable extends PluginI18NLanguageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return I18NLanguageTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('I18NLanguage');
    }
}
