<?php

/**
 * JobCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobCategoryTable extends PluginJobCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobCategory');
    }
}