<?php
/**
 * License class file
 */

/**
 * License
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class License extends PluginLicense
{
}
