<?php

/**
 * LicenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LicenseTable extends PluginLicenseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LicenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('License');
    }
}