<?php

/**
 * PluginOperationalCountry class file
 */

/**
 * PluginOperationalCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginOperationalCountry extends BaseOperationalCountry {

    public function getName() {
        return $this->getCountry()->getCouName();
    }
}