<?php

/**
 * PluginI18NGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginI18NGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginI18NGroupTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginI18NGroup');
    }
}
