<?php

/**
 * EmpBasicsalaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpBasicsalaryTable extends PluginEmpBasicsalaryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpBasicsalaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpBasicsalary');
    }
}