<?php

/**
 * EmpBasicsalary class file 
 */

/**
 * EmpBasicsalary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\pim
 */
class EmpBasicsalary extends PluginEmpBasicsalary
{
}
