<?php
/**
 * EmpJobtitleHistory class file
 */

/**
 * EmpJobtitleHistory 
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\pim
 */
class EmpJobtitleHistory extends PluginEmpJobtitleHistory
{
}
