<?php

/**
 * EmpJobtitleHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpJobtitleHistoryTable extends PluginEmpJobtitleHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpJobtitleHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpJobtitleHistory');
    }
}