<?php

/**
 * EmpTerminationReasonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpTerminationReasonTable extends PluginEmpTerminationReasonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpTerminationReasonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpTerminationReason');
    }
}