<?php

/**
 * EmpUsTaxExemption class file
 */

/**
 * EmpUsTaxExemption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\pim
 */
class EmpUsTaxExemption extends PluginEmpUsTaxExemption
{
}
