<?php

/**
 * PluginJobInterviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJobInterviewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJobInterviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJobInterview');
    }
}