<?php

/**
 * LeaveRequestCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveRequestCommentTable extends PluginLeaveRequestCommentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveRequestCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveRequestComment');
    }
}