<?php

/**
 * BaseLeaveStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $id                  Type: integer(4), primary key
 * @property int          $status              Type: integer(2)
 * @property string       $name                Type: string(100)
 *  
 * @method int            getId()              Type: integer(4), primary key
 * @method int            getStatus()          Type: integer(2)
 * @method string         getName()            Type: string(100)
 *  
 * @method LeaveStatus    setId(int $val)      Type: integer(4), primary key
 * @method LeaveStatus    setStatus(int $val)  Type: integer(2)
 * @method LeaveStatus    setName(string $val) Type: string(100)
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_status');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}