<?php

/**
 * BaseLeavePeriodHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                 $id                                Type: integer(4), primary key
 * @property int                 $leave_period_start_month          Type: integer(7)
 * @property int                 $leave_period_start_day            Type: integer(7)
 * @property string              $created_at                        Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 *  
 * @method int                   getId()                            Type: integer(4), primary key
 * @method int                   getLeavePeriodStartMonth()         Type: integer(7)
 * @method int                   getLeavePeriodStartDay()           Type: integer(7)
 * @method string                getCreatedAt()                     Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 *  
 * @method LeavePeriodHistory    setId(int $val)                    Type: integer(4), primary key
 * @method LeavePeriodHistory    setLeavePeriodStartMonth(int $val) Type: integer(7)
 * @method LeavePeriodHistory    setLeavePeriodStartDay(int $val)   Type: integer(7)
 * @method LeavePeriodHistory    setCreatedAt(string $val)          Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeavePeriodHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_period_history');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('leave_period_start_month', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('leave_period_start_day', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('created_at', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}