<?php

/**
 * BaseHoliday
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                 $id                                            Type: integer(4), primary key
 * @property int                 $recurring                                     Type: integer(1), default "0"
 * @property string              $description                                   Type: string(2147483647)
 * @property string              $date                                          Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @property int                 $length                                        Type: integer(4)
 * @property int                 $operational_country_id                        Type: integer(4)
 * @property OperationalCountry  $OperationalCountry                            
 *  
 * @method int                   getId()                                        Type: integer(4), primary key
 * @method int                   getRecurring()                                 Type: integer(1), default "0"
 * @method string                getDescription()                               Type: string(2147483647)
 * @method string                getDate()                                      Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @method int                   getLength()                                    Type: integer(4)
 * @method int                   getOperationalCountryId()                      Type: integer(4)
 * @method OperationalCountry    getOperationalCountry()                        
 *  
 * @method Holiday               setId(int $val)                                Type: integer(4), primary key
 * @method Holiday               setRecurring(int $val)                         Type: integer(1), default "0"
 * @method Holiday               setDescription(string $val)                    Type: string(2147483647)
 * @method Holiday               setDate(string $val)                           Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @method Holiday               setLength(int $val)                            Type: integer(4)
 * @method Holiday               setOperationalCountryId(int $val)              Type: integer(4)
 * @method Holiday               setOperationalCountry(OperationalCountry $val) 
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHoliday extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_holiday');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('recurring', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 2147483647, array(
             'type' => 'string',
             'length' => 2147483647,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('length', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('operational_country_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OperationalCountry', array(
             'local' => 'operational_country_id',
             'foreign' => 'id'));
    }
}