<?php

/**
 * PluginSystemUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSystemUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSystemUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSystemUser');
    }
}