<?php

/**
 * PluginDataGroupScreenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDataGroupScreenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDataGroupScreenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDataGroupScreen');
    }
}