<?php

/**
 * PayGrade class file
 */

/**
 * PayGrade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class PayGrade extends PluginPayGrade
{
}
