<?php

/**
 * ProjectActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjectActivity extends PluginProjectActivity {

	const ACTIVE_PROJECT_ACTIVITY = 0;
	const DELETED_PROJECT_ACTIVITY = 1;
	
	
}
