<?php

/**
 * PluginTimesheetItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTimesheetItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTimesheetItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTimesheetItem');
    }
}