[supervisord] 
nodaemon=true 
user=root 
loglevel=debug
logfile=/deeptune/supervisord.log 
 
[program:apache2] 
command=/usr/sbin/apache2ctl -D FOREGROUND 
autostart=true 
autorestart=true 
stderr_logfile=/var/log/apache2.err.log 
stdout_logfile=/var/log/apache2.out.log 

[program:mysql]
command=/bin/bash -c "service mysql start && tail -f /var/log/mysql/error.log"
autostart=true
autorestart=true
stderr_logfile=/var/log/mysql.err.log
stdout_logfile=/var/log/mysql.out.log

