<?php

/**
 * PluginAdvancedReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAdvancedReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAdvancedReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAdvancedReport');
    }
}