<?php

/**
 * ReportingMethodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportingMethodTable extends PluginReportingMethodTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportingMethodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReportingMethod');
    }
}