<?php

/**
 *  Customer class file
 */

/**
 * Customer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class Customer extends PluginCustomer {
	const NO_OF_RECORDS_PER_PAGE = 50;
	const DELETED = 1;
	const ACTIVE = 0;
}
