<?php

/**
 * LeavePeriodHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeavePeriodHistoryTable extends PluginLeavePeriodHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeavePeriodHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeavePeriodHistory');
    }
}