<?php

/**
 * BaseEmpChildren
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $emp_number                Type: integer(4), primary key
 * @property float        $seqno                     Type: decimal(2), primary key
 * @property string       $name                      Type: string(100)
 * @property string       $dob                       Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @property Employee     $Employee                  
 *  
 * @method int            getEmpNumber()             Type: integer(4), primary key
 * @method float          getSeqno()                 Type: decimal(2), primary key
 * @method string         getName()                  Type: string(100)
 * @method string         getDob()                   Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @method Employee       getEmployee()              
 *  
 * @method EmpChildren    setEmpNumber(int $val)     Type: integer(4), primary key
 * @method EmpChildren    setSeqno(float $val)       Type: decimal(2), primary key
 * @method EmpChildren    setName(string $val)       Type: string(100)
 * @method EmpChildren    setDob(string $val)        Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @method EmpChildren    setEmployee(Employee $val) 
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpChildren extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_children');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('ec_seqno as seqno', 'decimal', 2, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('ec_name as name', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('ec_date_of_birth as dob', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}