<?php

/**
 * BaseEmploymentStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $employees
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getEmployees() Returns the current record's "employees" collection
 * @method EmploymentStatus    setId()        Sets the current record's "id" value
 * @method EmploymentStatus    setName()      Sets the current record's "name" value
 * @method EmploymentStatus    setEmployees() Sets the current record's "employees" collection
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmploymentStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_employment_status');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Employee as employees', array(
             'local' => 'id',
             'foreign' => 'emp_status'));
    }
}