<?php

/**
 * BaseOrganization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $taxId
 * @property string $registraionNumber
 * @property string $phone
 * @property string $fax
 * @property string $email
 * @property string $country
 * @property string $province
 * @property string $city
 * @property string $zipCode
 * @property string $street1
 * @property string $street2
 * @property string $note
 * 
 * @method integer      getId()                Returns the current record's "id" value
 * @method string       getName()              Returns the current record's "name" value
 * @method string       getTaxId()             Returns the current record's "taxId" value
 * @method string       getRegistraionNumber() Returns the current record's "registraionNumber" value
 * @method string       getPhone()             Returns the current record's "phone" value
 * @method string       getFax()               Returns the current record's "fax" value
 * @method string       getEmail()             Returns the current record's "email" value
 * @method string       getCountry()           Returns the current record's "country" value
 * @method string       getProvince()          Returns the current record's "province" value
 * @method string       getCity()              Returns the current record's "city" value
 * @method string       getZipCode()           Returns the current record's "zipCode" value
 * @method string       getStreet1()           Returns the current record's "street1" value
 * @method string       getStreet2()           Returns the current record's "street2" value
 * @method string       getNote()              Returns the current record's "note" value
 * @method Organization setId()                Sets the current record's "id" value
 * @method Organization setName()              Sets the current record's "name" value
 * @method Organization setTaxId()             Sets the current record's "taxId" value
 * @method Organization setRegistraionNumber() Sets the current record's "registraionNumber" value
 * @method Organization setPhone()             Sets the current record's "phone" value
 * @method Organization setFax()               Sets the current record's "fax" value
 * @method Organization setEmail()             Sets the current record's "email" value
 * @method Organization setCountry()           Sets the current record's "country" value
 * @method Organization setProvince()          Sets the current record's "province" value
 * @method Organization setCity()              Sets the current record's "city" value
 * @method Organization setZipCode()           Sets the current record's "zipCode" value
 * @method Organization setStreet1()           Sets the current record's "street1" value
 * @method Organization setStreet2()           Sets the current record's "street2" value
 * @method Organization setNote()              Sets the current record's "note" value
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganization extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_organization_gen_info');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('tax_id as taxId', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('registration_number as registraionNumber', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('phone', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('fax', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('email', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('country', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('province', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('city', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('zip_code as zipCode', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('street1', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('street2', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}