<?php

/**
 * BaseI18NGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                   $id                                         Type: integer, primary key
 * @property string                                $name                                       Type: string(255)
 * @property string                                $title                                      Type: string(255)
 * @property Doctrine_Collection|I18NLangString[]  $I18NLangString                             
 *  
 * @method int                                     getId()                                     Type: integer, primary key
 * @method string                                  getName()                                   Type: string(255)
 * @method string                                  getTitle()                                  Type: string(255)
 * @method Doctrine_Collection|I18NLangString[]    getI18NLangString()                         
 *  
 * @method I18NGroup                               setId(int $val)                             Type: integer, primary key
 * @method I18NGroup                               setName(string $val)                        Type: string(255)
 * @method I18NGroup                               setTitle(string $val)                       Type: string(255)
 * @method I18NGroup                               setI18NLangString(Doctrine_Collection $val) 
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseI18NGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_i18n_group');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('I18NLangString', array(
             'local' => 'id',
             'foreign' => 'groupId'));
    }
}
