<?php

/**
 * BaseLikeOnShare
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $id                            Type: integer, primary key
 * @property int          $share_id                      Type: integer
 * @property int          $employee_number               Type: integer(7)
 * @property string       $like_time                     Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property Employee     $employeeLike                  
 * @property Share        $ShareLike                     
 *  
 * @method int            getId()                        Type: integer, primary key
 * @method int            getShareId()                   Type: integer
 * @method int            getEmployeeNumber()            Type: integer(7)
 * @method string         getLikeTime()                  Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Employee       getEmployeeLike()              
 * @method Share          getShareLike()                 
 *  
 * @method LikeOnShare    setId(int $val)                Type: integer, primary key
 * @method LikeOnShare    setShareId(int $val)           Type: integer
 * @method LikeOnShare    setEmployeeNumber(int $val)    Type: integer(7)
 * @method LikeOnShare    setLikeTime(string $val)       Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method LikeOnShare    setEmployeeLike(Employee $val) 
 * @method LikeOnShare    setShareLike(Share $val)       
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLikeOnShare extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_buzz_like_on_share');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '',
             ));
        $this->hasColumn('share_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('employee_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('like_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee as employeeLike', array(
             'local' => 'employee_number',
             'foreign' => 'empNumber'));

        $this->hasOne('Share as ShareLike', array(
             'local' => 'share_id',
             'foreign' => 'id'));
    }
}