INSERT INTO `hs_hr_country`(`cou_code`, `name`, `cou_name`, `iso3`, `numcode`) VALUES ('AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 4),
    ('AL', 'ALBANIA', 'Albania', 'ALB', 8),
    ('DZ', 'ALGERIA', 'Algeria', 'DZA', 12),
    ('AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 16),
    ('AD', 'ANDORRA', 'Andorra', 'AND', 20),
    ('AO', 'ANGOLA', 'Angola', 'AGO', 24),
    ('AI', 'ANGUILLA', 'Anguilla', 'AIA', 660),
    ('AQ', 'ANTARCTICA', 'Antarctica', NULL, NULL),
    ('AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 28),
    ('AR', 'ARGENTINA', 'Argentina', 'ARG', 32),
    ('AM', 'ARMENIA', 'Armenia', 'ARM', 51),
    ('AW', 'ARUBA', 'Aruba', 'ABW', 533),
    ('AU', 'AUSTRALIA', 'Australia', 'AUS', 36),
    ('AT', 'AUSTRIA', 'Austria', 'AUT', 40),
    ('AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 31),
    ('BS', 'BAHAMAS', 'Bahamas', 'BHS', 44),
    ('BH', 'BAHRAIN', 'Bahrain', 'BHR', 48),
    ('BD', 'BANGLADESH', 'Bangladesh', 'BGD', 50),
    ('BB', 'BARBADOS', 'Barbados', 'BRB', 52),
    ('BY', 'BELARUS', 'Belarus', 'BLR', 112),
    ('BE', 'BELGIUM', 'Belgium', 'BEL', 56),
    ('BZ', 'BELIZE', 'Belize', 'BLZ', 84),
    ('BJ', 'BENIN', 'Benin', 'BEN', 204),
    ('BM', 'BERMUDA', 'Bermuda', 'BMU', 60),
    ('BT', 'BHUTAN', 'Bhutan', 'BTN', 64),
    ('BO', 'BOLIVIA', 'Bolivia', 'BOL', 68),
    ('BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 70),
    ('BW', 'BOTSWANA', 'Botswana', 'BWA', 72),
    ('BV', 'BOUVET ISLAND', 'Bouvet Island', NULL, NULL),
    ('BR', 'BRAZIL', 'Brazil', 'BRA', 76),
    ('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', NULL, NULL),
    ('BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 96),
    ('BG', 'BULGARIA', 'Bulgaria', 'BGR', 100),
    ('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 854),
    ('BI', 'BURUNDI', 'Burundi', 'BDI', 108),
    ('KH', 'CAMBODIA', 'Cambodia', 'KHM', 116),
    ('CM', 'CAMEROON', 'Cameroon', 'CMR', 120),
    ('CA', 'CANADA', 'Canada', 'CAN', 124),
    ('CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 132),
    ('KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 136),
    ('CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 140),
    ('TD', 'CHAD', 'Chad', 'TCD', 148),
    ('CL', 'CHILE', 'Chile', 'CHL', 152),
    ('CN', 'CHINA', 'China', 'CHN', 156),
    ('CX', 'CHRISTMAS ISLAND', 'Christmas Island', NULL, NULL),
    ('CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, NULL),
    ('CO', 'COLOMBIA', 'Colombia', 'COL', 170),
    ('KM', 'COMOROS', 'Comoros', 'COM', 174),
    ('CG', 'CONGO', 'Congo', 'COG', 178),
    ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', 180),
    ('CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 184),
    ('CR', 'COSTA RICA', 'Costa Rica', 'CRI', 188),
    ('CI', 'COTE D''IVOIRE', 'Cote D''Ivoire', 'CIV', 384),
    ('HR', 'CROATIA', 'Croatia', 'HRV', 191),
    ('CU', 'CUBA', 'Cuba', 'CUB', 192),
    ('CY', 'CYPRUS', 'Cyprus', 'CYP', 196),
    ('CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', 203),
    ('DK', 'DENMARK', 'Denmark', 'DNK', 208),
    ('DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 262),
    ('DM', 'DOMINICA', 'Dominica', 'DMA', 212),
    ('DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 214),
    ('EC', 'ECUADOR', 'Ecuador', 'ECU', 218),
    ('EG', 'EGYPT', 'Egypt', 'EGY', 818),
    ('SV', 'EL SALVADOR', 'El Salvador', 'SLV', 222),
    ('GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 226),
    ('ER', 'ERITREA', 'Eritrea', 'ERI', 232),
    ('EE', 'ESTONIA', 'Estonia', 'EST', 233),
    ('ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 231),
    ('FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 238),
    ('FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', 234),
    ('FJ', 'FIJI', 'Fiji', 'FJI', 242),
    ('FI', 'FINLAND', 'Finland', 'FIN', 246),
    ('FR', 'FRANCE', 'France', 'FRA', 250),
    ('GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', 254),
    ('PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 258),
    ('TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', NULL, NULL),
    ('GA', 'GABON', 'Gabon', 'GAB', 266),
    ('GM', 'GAMBIA', 'Gambia', 'GMB', 270),
    ('GE', 'GEORGIA', 'Georgia', 'GEO', 268),
    ('DE', 'GERMANY', 'Germany', 'DEU', 276),
    ('GH', 'GHANA', 'Ghana', 'GHA', 288),
    ('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 292),
    ('GR', 'GREECE', 'Greece', 'GRC', 300),
    ('GL', 'GREENLAND', 'Greenland', 'GRL', 304),
    ('GD', 'GRENADA', 'Grenada', 'GRD', 308),
    ('GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', 312),
    ('GU', 'GUAM', 'Guam', 'GUM', 316),
    ('GT', 'GUATEMALA', 'Guatemala', 'GTM', 320),
    ('GN', 'GUINEA', 'Guinea', 'GIN', 324),
    ('GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 624),
    ('GY', 'GUYANA', 'Guyana', 'GUY', 328),
    ('HT', 'HAITI', 'Haiti', 'HTI', 332),
    ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', NULL, NULL),
    ('VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', 336),
    ('HN', 'HONDURAS', 'Honduras', 'HND', 340),
    ('HK', 'HONG KONG', 'Hong Kong', 'HKG', 344),
    ('HU', 'HUNGARY', 'Hungary', 'HUN', 348),
    ('IS', 'ICELAND', 'Iceland', 'ISL', 352),
    ('IN', 'INDIA', 'India', 'IND', 356),
    ('ID', 'INDONESIA', 'Indonesia', 'IDN', 360),
    ('IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 364),
    ('IQ', 'IRAQ', 'Iraq', 'IRQ', 368),
    ('IE', 'IRELAND', 'Ireland', 'IRL', 372),
    ('IL', 'ISRAEL', 'Israel', 'ISR', 376),
    ('IT', 'ITALY', 'Italy', 'ITA', 380),
    ('JM', 'JAMAICA', 'Jamaica', 'JAM', 388),
    ('JP', 'JAPAN', 'Japan', 'JPN', 392),
    ('JO', 'JORDAN', 'Jordan', 'JOR', 400),
    ('KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 398),
    ('KE', 'KENYA', 'Kenya', 'KEN', 404),
    ('KI', 'KIRIBATI', 'Kiribati', 'KIR', 296),
    ('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Korea, Democratic People''s Republic of', 'PRK', 408),
    ('KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', 410),
    ('KW', 'KUWAIT', 'Kuwait', 'KWT', 414),
    ('KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 417),
    ('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', 418),
    ('LV', 'LATVIA', 'Latvia', 'LVA', 428),
    ('LB', 'LEBANON', 'Lebanon', 'LBN', 422),
    ('LS', 'LESOTHO', 'Lesotho', 'LSO', 426),
    ('LR', 'LIBERIA', 'Liberia', 'LBR', 430),
    ('LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 434),
    ('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 438),
    ('LT', 'LITHUANIA', 'Lithuania', 'LTU', 440),
    ('LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 442),
    ('MO', 'MACAO', 'Macao', 'MAC', 446),
    ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 807),
    ('MG', 'MADAGASCAR', 'Madagascar', 'MDG', 450),
    ('MW', 'MALAWI', 'Malawi', 'MWI', 454),
    ('MY', 'MALAYSIA', 'Malaysia', 'MYS', 458),
    ('MV', 'MALDIVES', 'Maldives', 'MDV', 462),
    ('ML', 'MALI', 'Mali', 'MLI', 466),
    ('MT', 'MALTA', 'Malta', 'MLT', 470),
    ('MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 584),
    ('MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 474),
    ('MR', 'MAURITANIA', 'Mauritania', 'MRT', 478),
    ('MU', 'MAURITIUS', 'Mauritius', 'MUS', 480),
    ('YT', 'MAYOTTE', 'Mayotte', NULL, NULL),
    ('MX', 'MEXICO', 'Mexico', 'MEX', 484),
    ('FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 583),
    ('MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', 498),
    ('MC', 'MONACO', 'Monaco', 'MCO', 492),
    ('MN', 'MONGOLIA', 'Mongolia', 'MNG', 496),
    ('MS', 'MONTSERRAT', 'Montserrat', 'MSR', 500),
    ('MA', 'MOROCCO', 'Morocco', 'MAR', 504),
    ('MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 508),
    ('MM', 'MYANMAR', 'Myanmar', 'MMR', 104),
    ('NA', 'NAMIBIA', 'Namibia', 'NAM', 516),
    ('NR', 'NAURU', 'Nauru', 'NRU', 520),
    ('NP', 'NEPAL', 'Nepal', 'NPL', 524),
    ('NL', 'NETHERLANDS', 'Netherlands', 'NLD', 528),
    ('AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', 530),
    ('NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 540),
    ('NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 554),
    ('NI', 'NICARAGUA', 'Nicaragua', 'NIC', 558),
    ('NE', 'NIGER', 'Niger', 'NER', 562),
    ('NG', 'NIGERIA', 'Nigeria', 'NGA', 566),
    ('NU', 'NIUE', 'Niue', 'NIU', 570),
    ('NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 574),
    ('MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 580),
    ('NO', 'NORWAY', 'Norway', 'NOR', 578),
    ('OM', 'OMAN', 'Oman', 'OMN', 512),
    ('PK', 'PAKISTAN', 'Pakistan', 'PAK', 586),
    ('PW', 'PALAU', 'Palau', 'PLW', 585),
    ('PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL, NULL),
    ('PA', 'PANAMA', 'Panama', 'PAN', 591),
    ('PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 598),
    ('PY', 'PARAGUAY', 'Paraguay', 'PRY', 600),
    ('PE', 'PERU', 'Peru', 'PER', 604),
    ('PH', 'PHILIPPINES', 'Philippines', 'PHL', 608),
    ('PN', 'PITCAIRN', 'Pitcairn', 'PCN', 612),
    ('PL', 'POLAND', 'Poland', 'POL', 616),
    ('PT', 'PORTUGAL', 'Portugal', 'PRT', 620),
    ('PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 630),
    ('QA', 'QATAR', 'Qatar', 'QAT', 634),
    ('RE', 'REUNION', 'Reunion', 'REU', 638),
    ('RO', 'ROMANIA', 'Romania', 'ROM', 642),
    ('RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 643),
    ('RW', 'RWANDA', 'Rwanda', 'RWA', 646),
    ('SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 654),
    ('KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 659),
    ('LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 662),
    ('PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', 666),
    ('VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 670),
    ('WS', 'SAMOA', 'Samoa', 'WSM', 882),
    ('SM', 'SAN MARINO', 'San Marino', 'SMR', 674),
    ('ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 678),
    ('SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 682),
    ('SN', 'SENEGAL', 'Senegal', 'SEN', 686),
    ('CS', 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro', NULL, NULL),
    ('SC', 'SEYCHELLES', 'Seychelles', 'SYC', 690),
    ('SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 694),
    ('SG', 'SINGAPORE', 'Singapore', 'SGP', 702),
    ('SK', 'SLOVAKIA', 'Slovakia', 'SVK', 703),
    ('SI', 'SLOVENIA', 'Slovenia', 'SVN', 705),
    ('SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 90),
    ('SO', 'SOMALIA', 'Somalia', 'SOM', 706),
    ('ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 710),
    ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', NULL, NULL),
    ('ES', 'SPAIN', 'Spain', 'ESP', 724),
    ('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 144),
    ('SD', 'SUDAN', 'Sudan', 'SDN', 736),
    ('SR', 'SURINAME', 'Suriname', 'SUR', 740),
    ('SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', 744),
    ('SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 748),
    ('SE', 'SWEDEN', 'Sweden', 'SWE', 752),
    ('CH', 'SWITZERLAND', 'Switzerland', 'CHE', 756),
    ('SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 760),
    ('TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan', 'TWN', 158),
    ('TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 762),
    ('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', 834),
    ('TH', 'THAILAND', 'Thailand', 'THA', 764),
    ('TL', 'TIMOR-LESTE', 'Timor-Leste', NULL, NULL),
    ('TG', 'TOGO', 'Togo', 'TGO', 768),
    ('TK', 'TOKELAU', 'Tokelau', 'TKL', 772),
    ('TO', 'TONGA', 'Tonga', 'TON', 776),
    ('TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 780),
    ('TN', 'TUNISIA', 'Tunisia', 'TUN', 788),
    ('TR', 'TURKEY', 'Turkey', 'TUR', 792),
    ('TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 795),
    ('TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 796),
    ('TV', 'TUVALU', 'Tuvalu', 'TUV', 798),
    ('UG', 'UGANDA', 'Uganda', 'UGA', 800),
    ('UA', 'UKRAINE', 'Ukraine', 'UKR', 804),
    ('AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 784),
    ('GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', 826),
    ('US', 'UNITED STATES', 'United States', 'USA', 840),
    ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', NULL, NULL),
    ('UY', 'URUGUAY', 'Uruguay', 'URY', 858),
    ('UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 860),
    ('VU', 'VANUATU', 'Vanuatu', 'VUT', 548),
    ('VE', 'VENEZUELA', 'Venezuela', 'VEN', 862),
    ('VN', 'VIET NAM', 'Viet Nam', 'VNM', 704),
    ('VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', 92),
    ('VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', 850),
    ('WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', 876),
    ('EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', 732),
    ('YE', 'YEMEN', 'Yemen', 'YEM', 887),
    ('ZM', 'ZAMBIA', 'Zambia', 'ZMB', 894),
    ('ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 716);

  
INSERT INTO `hs_hr_currency_type`(`code`, `currency_id`, `currency_name`) VALUES (3, 'AED', 'Utd. Arab Emir. Dirham'),
    (4, 'AFN', 'Afghanistan Afghani'),
    (5, 'ALL', 'Albanian Lek'),
    (6, 'ANG', 'NL Antillian Guilder'),
    (7, 'AOR', 'Angolan New Kwanza'),
    (177, 'ARP', 'Argentina Pesos'),
    (8, 'ARS', 'Argentine Peso'),
    (10, 'AUD', 'Australian Dollar'),
    (11, 'AWG', 'Aruban Florin'),
    (12, 'BBD', 'Barbados Dollar'),
    (13, 'BDT', 'Bangladeshi Taka'),
    (15, 'BGL', 'Bulgarian Lev'),
    (16, 'BHD', 'Bahraini Dinar'),
    (17, 'BIF', 'Burundi Franc'),
    (18, 'BMD', 'Bermudian Dollar'),
    (19, 'BND', 'Brunei Dollar'),
    (20, 'BOB', 'Bolivian Boliviano'),
    (21, 'BRL', 'Brazilian Real'),
    (22, 'BSD', 'Bahamian Dollar'),
    (23, 'BTN', 'Bhutan Ngultrum'),
    (24, 'BWP', 'Botswana Pula'),
    (25, 'BZD', 'Belize Dollar'),
    (26, 'CAD', 'Canadian Dollar'),
    (27, 'CHF', 'Swiss Franc'),
    (28, 'CLP', 'Chilean Peso'),
    (29, 'CNY', 'Chinese Yuan Renminbi'),
    (30, 'COP', 'Colombian Peso'),
    (31, 'CRC', 'Costa Rican Colon'),
    (171, 'CZK', 'Czech Koruna'),
    (32, 'CUP', 'Cuban Peso'),
    (33, 'CVE', 'Cape Verde Escudo'),
    (34, 'CYP', 'Cyprus Pound'),
    (37, 'DJF', 'Djibouti Franc'),
    (38, 'DKK', 'Danish Krona'),
    (39, 'DOP', 'Dominican Peso'),
    (40, 'DZD', 'Algerian Dinar'),
    (41, 'ECS', 'Ecuador Sucre'),
    (43, 'EEK', 'Estonian Krona'),
    (44, 'EGP', 'Egyptian Pound'),
    (46, 'ETB', 'Ethiopian Birr'),
    (42, 'EUR', 'Euro'),
    (48, 'FJD', 'Fiji Dollar'),
    (49, 'FKP', 'Falkland Islands Pound'),
    (51, 'GBP', 'Pound Sterling'),
    (52, 'GHC', 'Ghanaian Cedi'),
    (53, 'GIP', 'Gibraltar Pound'),
    (54, 'GMD', 'Gambian Dalasi'),
    (55, 'GNF', 'Guinea Franc'),
    (57, 'GTQ', 'Guatemalan Quetzal'),
    (58, 'GYD', 'Guyanan Dollar'),
    (59, 'HKD', 'Hong Kong Dollar'),
    (60, 'HNL', 'Honduran Lempira'),
    (61, 'HRK', 'Croatian Kuna'),
    (62, 'HTG', 'Haitian Gourde'),
    (63, 'HUF', 'Hungarian Forint'),
    (64, 'IDR', 'Indonesian Rupiah'),
    (66, 'ILS', 'Israeli New Shekel'),
    (67, 'INR', 'Indian Rupee'),
    (68, 'IQD', 'Iraqi Dinar'),
    (69, 'IRR', 'Iranian Rial'),
    (70, 'ISK', 'Iceland Krona'),
    (72, 'JMD', 'Jamaican Dollar'),
    (73, 'JOD', 'Jordanian Dinar'),
    (74, 'JPY', 'Japanese Yen'),
    (75, 'KES', 'Kenyan Shilling'),
    (76, 'KHR', 'Kampuchean Riel'),
    (77, 'KMF', 'Comoros Franc'),
    (78, 'KPW', 'North Korean Won'),
    (79, 'KRW', 'Korean Won'),
    (80, 'KWD', 'Kuwaiti Dinar'),
    (81, 'KYD', 'Cayman Islands Dollar'),
    (82, 'KZT', 'Kazakhstan Tenge'),
    (83, 'LAK', 'Lao Kip'),
    (84, 'LBP', 'Lebanese Pound'),
    (85, 'LKR', 'Sri Lanka Rupee'),
    (86, 'LRD', 'Liberian Dollar'),
    (87, 'LSL', 'Lesotho Loti'),
    (88, 'LTL', 'Lithuanian Litas'),
    (90, 'LVL', 'Latvian Lats'),
    (91, 'LYD', 'Libyan Dinar'),
    (92, 'MAD', 'Moroccan Dirham'),
    (93, 'MGF', 'Malagasy Franc'),
    (94, 'MMK', 'Myanmar Kyat'),
    (95, 'MNT', 'Mongolian Tugrik'),
    (96, 'MOP', 'Macau Pataca'),
    (97, 'MRO', 'Mauritanian Ouguiya'),
    (98, 'MTL', 'Maltese Lira'),
    (99, 'MUR', 'Mauritius Rupee'),
    (100, 'MVR', 'Maldive Rufiyaa'),
    (101, 'MWK', 'Malawi Kwacha'),
    (102, 'MXN', 'Mexican New Peso'),
    (172, 'MXP', 'Mexican Peso'),
    (103, 'MYR', 'Malaysian Ringgit'),
    (104, 'MZM', 'Mozambique Metical'),
    (105, 'NAD', 'Namibia Dollar'),
    (106, 'NGN', 'Nigerian Naira'),
    (107, 'NIO', 'Nicaraguan Cordoba Oro'),
    (109, 'NOK', 'Norwegian Krona'),
    (110, 'NPR', 'Nepalese Rupee'),
    (111, 'NZD', 'New Zealand Dollar'),
    (112, 'OMR', 'Omani Rial'),
    (113, 'PAB', 'Panamanian Balboa'),
    (114, 'PEN', 'Peruvian Nuevo Sol'),
    (115, 'PGK', 'Papua New Guinea Kina'),
    (116, 'PHP', 'Philippine Peso'),
    (117, 'PKR', 'Pakistan Rupee'),
    (118, 'PLN', 'Polish Zloty'),
    (120, 'PYG', 'Paraguay Guarani'),
    (121, 'QAR', 'Qatari Rial'),
    (122, 'ROL', 'Romanian Leu'),
    (123, 'RUB', 'Russian Rouble'),
    (180, 'RUR', 'Russia Rubles'),
    (124, 'SAR', 'South African Rand'),
    (125, 'SBD', 'Solomon Islands Dollar'),
    (126, 'SCR', 'Seychelles Rupee'),
    (127, 'SDD', 'Sudanese Dinar'),
    (128, 'SDP', 'Sudanese Pound'),
    (129, 'SEK', 'Swedish Krona'),
    (131, 'SGD', 'Singapore Dollar'),
    (132, 'SHP', 'St. Helena Pound'),
    (130, 'SKK', 'Slovak Koruna'),
    (135, 'SLL', 'Sierra Leone Leone'),
    (136, 'SOS', 'Somali Shilling'),
    (137, 'SRD', 'Surinamese Dollar'),
    (138, 'STD', 'Sao Tome/Principe Dobra'),
    (139, 'SVC', 'El Salvador Colon'),
    (140, 'SYP', 'Syrian Pound'),
    (141, 'SZL', 'Swaziland Lilangeni'),
    (142, 'THB', 'Thai Baht'),
    (143, 'TND', 'Tunisian Dinar'),
    (144, 'TOP', 'Tongan Pa''anga'),
    (145, 'TRL', 'Turkish Lira'),
    (146, 'TTD', 'Trinidad/Tobago Dollar'),
    (147, 'TWD', 'Taiwan Dollar'),
    (148, 'TZS', 'Tanzanian Shilling'),
    (149, 'UAH', 'Ukraine Hryvnia'),
    (150, 'UGX', 'Uganda Shilling'),
    (151, 'USD', 'United States Dollar'),
    (152, 'UYP', 'Uruguayan Peso'),
    (153, 'VEB', 'Venezuelan Bolivar'),
    (154, 'VND', 'Vietnamese Dong'),
    (155, 'VUV', 'Vanuatu Vatu'),
    (156, 'WST', 'Samoan Tala'),
    (158, 'XAF', 'CFA Franc BEAC'),
    (159, 'XAG', 'Silver (oz.)'),
    (160, 'XAU', 'Gold (oz.)'),
    (161, 'XCD', 'Eastern Caribbean Dollars'),
    (179, 'XDR', 'IMF Special Drawing Right'),
    (162, 'XOF', 'CFA Franc BCEAO'),
    (163, 'XPD', 'Palladium (oz.)'),
    (164, 'XPF', 'Franc des Comptoirs français du Pacifique'),
    (165, 'XPT', 'Platinum (oz.)'),
    (166, 'YER', 'Yemeni Riyal'),
    (167, 'YUM', 'Yugoslavian Dinar'),
    (175, 'YUN', 'Yugoslav Dinar'),
    (168, 'ZAR', 'South African Rand'),
    (176, 'ZMK', 'Zambian Kwacha'),
    (169, 'ZRN', 'New Zaire'),
    (170, 'ZWD', 'Zimbabwe Dollar');
  

INSERT INTO `hs_hr_province`(`id`, `province_name`, `province_code`, `cou_code`) VALUES (1, 'Alaska', 'AK', 'US'),
    (2, 'Alabama', 'AL', 'US'),
    (3, 'American Samoa', 'AS', 'US'),
    (4, 'Arizona', 'AZ', 'US'),
    (5, 'Arkansas', 'AR', 'US'),
    (6, 'California', 'CA', 'US'),
    (7, 'Colorado', 'CO', 'US'),
    (8, 'Connecticut', 'CT', 'US'),
    (9, 'Delaware', 'DE', 'US'),
    (10, 'District of Columbia', 'DC', 'US'),
    (11, 'Federated States of Micronesia', 'FM', 'US'),
    (12, 'Florida', 'FL', 'US'),
    (13, 'Georgia', 'GA', 'US'),
    (14, 'Guam', 'GU', 'US'),
    (15, 'Hawaii', 'HI', 'US'),
    (16, 'Idaho', 'ID', 'US'),
    (17, 'Illinois', 'IL', 'US'),
    (18, 'Indiana', 'IN', 'US'),
    (19, 'Iowa', 'IA', 'US'),
    (20, 'Kansas', 'KS', 'US'),
    (21, 'Kentucky', 'KY', 'US'),
    (22, 'Louisiana', 'LA', 'US'),
    (23, 'Maine', 'ME', 'US'),
    (24, 'Marshall Islands', 'MH', 'US'),
    (25, 'Maryland', 'MD', 'US'),
    (26, 'Massachusetts', 'MA', 'US'),
    (27, 'Michigan', 'MI', 'US'),
    (28, 'Minnesota', 'MN', 'US'),
    (29, 'Mississippi', 'MS', 'US'),
    (30, 'Missouri', 'MO', 'US'),
    (31, 'Montana', 'MT', 'US'),
    (32, 'Nebraska', 'NE', 'US'),
    (33, 'Nevada', 'NV', 'US'),
    (34, 'New Hampshire', 'NH', 'US'),
    (35, 'New Jersey', 'NJ', 'US'),
    (36, 'New Mexico', 'NM', 'US'),
    (37, 'New York', 'NY', 'US'),
    (38, 'North Carolina', 'NC', 'US'),
    (39, 'North Dakota', 'ND', 'US'),
    (40, 'Northern Mariana Islands', 'MP', 'US'),
    (41, 'Ohio', 'OH', 'US'),
    (42, 'Oklahoma', 'OK', 'US'),
    (43, 'Oregon', 'OR', 'US'),
    (44, 'Palau', 'PW', 'US'),
    (45, 'Pennsylvania', 'PA', 'US'),
    (46, 'Puerto Rico', 'PR', 'US'),
    (47, 'Rhode Island', 'RI', 'US'),
    (48, 'South Carolina', 'SC', 'US'),
    (49, 'South Dakota', 'SD', 'US'),
    (50, 'Tennessee', 'TN', 'US'),
    (51, 'Texas', 'TX', 'US'),
    (52, 'Utah', 'UT', 'US'),
    (53, 'Vermont', 'VT', 'US'),
    (54, 'Virgin Islands', 'VI', 'US'),
    (55, 'Virginia', 'VA', 'US'),
    (56, 'Washington', 'WA', 'US'),
    (57, 'West Virginia', 'WV', 'US'),
    (58, 'Wisconsin', 'WI', 'US'),
    (59, 'Wyoming', 'WY', 'US'),
    (60, 'Armed Forces Africa', 'AE', 'US'),
    (61, 'Armed Forces Americas (except Canada)', 'AA', 'US'),
    (62, 'Armed Forces Canada', 'AE', 'US'),
    (63, 'Armed Forces Europe', 'AE', 'US'),
    (64, 'Armed Forces Middle East', 'AE', 'US'),
    (65, 'Armed Forces Pacific', 'AP', 'US');

INSERT INTO `hs_hr_eec`(`eec_code`, `eec_desc`) VALUES ('EEC001', 'OFFICIALS AND ADMINISTRATORS'),
    ('EEC002', 'PROFESSIONALS'),
    ('EEC003', 'TECHNICIANS'),
    ('EEC004', 'PROTECTIVE SERVICE WORKERS'),
    ('EEC005', 'PARAPROFESSIONALS'),
    ('EEC006', 'ADMINISTRATIVE SUPPORT'),
    ('EEC007', 'SKILLED CRAFT WORKERS'),
    ('EEC008', 'SERVICE-MAINTENANCE');

INSERT INTO `hs_hr_empstat`(`estat_code`, `estat_name`) VALUES ('EST001', 'Full Time Contract'),
    ('EST002', 'Full Time Internship'),
    ('EST003', 'Full Time Permanent'),
    ('EST004', 'Part Time Contract'),
    ('EST005', 'Part Time Internship'),
    ('EST006', 'Part Time Permanent');

INSERT INTO `hs_hr_geninfo` VALUES ('001','','');
INSERT INTO `hs_hr_user_group` VALUES ('USG001','Admin','1');
INSERT INTO `hs_hr_db_version` VALUES ('DVR001','mysql4.1','initial DB','2005-10-10 00:00:00','2005-12-20 00:00:00',null,null);
INSERT INTO `hs_hr_file_version` VALUES ('FVR001',NULL,'Release 1','2006-03-15 00:00:00','2006-03-15 00:00:00',null,null,'file_ver_01');
INSERT INTO `hs_hr_versions` VALUES ('VER001','Release 1','2006-03-15 00:00:00','2006-03-15 00:00:00',null,null,0,'DVR001','FVR001','version 1.0');
INSERT INTO `hs_hr_module` VALUES ('MOD001','Admin','OrangeHRM','info@orangehrm.com','VER001','HR Admin'),
								  ('MOD002','PIM','OrangeHRM','info@orangehrm.com','VER001','HR Functions'),
								  ('MOD004','Report','OrangeHRM','info@orangehrm.com','VER001','Reporting'),
								  ('MOD005', 'Leave', 'OrangeHRM', 'info@orangehrm.com', 'VER001', 'Leave Tracking'),
								  ('MOD006', 'Time', 'OrangeHRM', 'info@orangehrm.com', 'VER001', 'Time Tracking'),
								  ('MOD007', 'Benefits', 'OrangeHRM', 'info@orangehrm.com', 'VER001', 'Benefits Tracking'),
 	 							('MOD008', 'Recruitment', 'OrangeHRM', 'info@orangehrm.com', 'VER001', 'Recruitment'),
 	 							('MOD009', 'Performance', 'OrangeHRM', 'info@orangehrm.com', 'VER001', 'Performance');
INSERT INTO `hs_hr_rights` ( `userg_id` , `mod_id` , `addition` , `editing` , `deletion` , `viewing` )
        VALUES  ('USG001', 'MOD001', '1', '1', '1', '1'),
		('USG001', 'MOD002', '1', '1', '1', '1'),
		('USG001', 'MOD004', '1', '1', '1', '1'),
		('USG001', 'MOD005', '1', '1', '1', '1'),
		('USG001', 'MOD006', '1', '1', '1', '1'),
		('USG001', 'MOD007', '1', '1', '1', '1'),
 	 	('USG001', 'MOD008', '1', '1', '1', '1'),
 	 	('USG001', 'MOD009', '1', '1', '1', '1');
INSERT INTO `hs_hr_compstructtree`(`title`, `description`, `loc_code`, `lft`, `rgt`, `id`, `parnt`, `dept_id`) VALUES ('', 'Parent Company', null , 1, 2, 1, 0, null);



INSERT INTO `hs_hr_weekends`(`day`, `length`) VALUES (1, 0),
    (2, 0),
    (3, 0),
    (4, 0),
    (5, 0),
    (6, 8),
    (7, 8);

INSERT INTO `hs_hr_empstat`
	(`estat_code`, `estat_name`)
	VALUES ('EST000', 'Terminated');

INSERT INTO `hs_hr_payperiod`(payperiod_code, payperiod_name) VALUES (1, 'Weekly'),
    (2, 'Bi Weekly'),
    (3, 'Semi Monthly'),
    (4, 'Monthly'),
    (5, 'Monthly on first pay of month.'),
    (6, 'Hourly');

INSERT INTO `hs_hr_config`(`key`, `value`) VALUES ('ldap_server', ''),
    ('ldap_domain_name', ''),
    ('ldap_port', ''),
    ('ldap_status', ''),
    ('hsp_current_plan', '0'),
    ('hsp_accrued_last_updated', '0000-00-00'),
    ('hsp_used_last_updated', '0000-00-00'),
    ('attendanceEmpEditSubmitted', 'No'),
    ('attendanceSupEditSubmitted', 'No'),
    ('pim_show_deprecated_fields', 0),
    ('showSSN', 0),
    ('showSIN', 0),
    ('showTaxExemptions', 0),
    ('timesheet_time_format', '1'),
    ('timesheet_period_set', 'No'),
    ('timesheet_period_and_start_date', '<TimesheetPeriod><PeriodType>Weekly</PeriodType><ClassName>WeeklyTimesheetPeriod</ClassName><StartDate>1</StartDate><Heading>Week</Heading></TimesheetPeriod>');

INSERT INTO `ohrm_emp_reporting_method`(`reporting_method_id`, `reporting_method_name`) VALUES(1, 'Direct'),
      (2, 'Indirect');


INSERT INTO `hs_hr_unique_id`(last_id, table_name, field_name) VALUES (0, 'hs_hr_nationality', 'nat_code'),
    (0, 'hs_hr_language', 'lang_code'),
    (0, 'hs_hr_customer', 'customer_id'),
    (0, 'hs_hr_job_title', 'jobtit_code'),
    (6, 'hs_hr_empstat', 'estat_code'),
    (8, 'hs_hr_eec', 'eec_code'),
    (0, 'hs_hr_licenses', 'licenses_code'),
    (0, 'hs_hr_employee', 'emp_number'),
    (0, 'hs_hr_location', 'loc_code'),
    (0, 'hs_hr_membership', 'membship_code'),
    (0, 'hs_hr_membership_type', 'membtype_code'),
    (6, 'hs_hr_module', 'mod_id'),
    (0, 'hs_hr_education', 'edu_code'),
    (0, 'hs_hr_ethnic_race', 'ethnic_race_code'),
    (0, 'hs_hr_skill', 'skill_code'),
    (1, 'hs_hr_user_group', 'userg_id'),
    (1, 'hs_hr_users', 'id'),
    (0, 'hs_pr_salary_grade', 'sal_grd_code'),
    (0, 'hs_hr_empreport', 'rep_code'),
    (0, 'hs_hr_leave', 'leave_id'),
    (0, 'hs_hr_leavetype', 'leave_type_id'),
    (0, 'hs_hr_holidays', 'holiday_id'),
    (0, 'hs_hr_project', 'project_id'),
    (1, 'hs_hr_compstructtree', 'id'),
    (0, 'hs_hr_leave_requests', 'leave_request_id'),
    (0, 'hs_hr_project_activity', 'activity_id'),
    (0, 'hs_hr_workshift', 'workshift_id'),
    (0, 'hs_hr_custom_export', 'export_id'),
    (0, 'hs_hr_custom_import', 'import_id'),
    (0, 'hs_hr_pay_period', 'id'),
    (0, 'hs_hr_hsp_summary', 'summary_id'),
    (0, 'hs_hr_hsp_payment_request', 'id'),
    (0, 'hs_hr_job_spec', 'jobspec_id'),
    (0, 'hs_hr_kpi', 'id'),
    (0, 'hs_hr_performance_review', 'id'),
    (0, 'hs_hr_leave_period', 'leave_period_id'),
    (2, 'ohrm_emp_reporting_method', 'reporting_method_id'),
    (0, 'ohrm_timesheet', 'timesheet_id'),
    (0, 'ohrm_timesheet_action_log', 'timesheet_action_log_id'),
    (0, 'ohrm_timesheet_item', 'timesheet_item_id'),
    (0,'ohrm_attendance_record', 'id'),
    (0, 'ohrm_job_vacancy', 'id'),
    (0, 'ohrm_job_candidate', 'id'),
    (80,'ohrm_workflow_state_machine', 'id'),
    (0, 'ohrm_job_candidate_attachment', 'id'),
    (0, 'ohrm_job_vacancy_attachment', 'id'),
    (0, 'ohrm_job_candidate_vacancy', 'id'),
    (0, 'ohrm_job_candidate_history', 'id'),
    (0, 'ohrm_job_interview', 'id');

INSERT INTO `ohrm_workflow_state_machine` VALUES ('1','0','INITIAL','SYSTEM','7','NOT SUBMITTED'),
                                   ('2','0','SUBMITTED','ADMIN','2','APPROVED'),
                                   ('3','0','SUBMITTED','ADMIN','3','REJECTED'),
                                   ('4','0','SUBMITTED','ADMIN','0','SUBMITTED'),
                                   ('5','0','SUBMITTED','ADMIN','5','SUBMITTED'),
                                   ('6','0','SUBMITTED','SUPERVISOR','2','APPROVED'),
                                   ('7','0','SUBMITTED','SUPERVISOR','3','REJECTED'),
                                   ('8','0','SUBMITTED','SUPERVISOR','5','SUBMITTED'),
                                   ('9','0','SUBMITTED','SUPERVISOR','0','SUBMITTED'),
                                   ('10','0','SUBMITTED','ESS USER','0','SUBMITTED'),
                                   ('11','0','SUBMITTED','ESS USER','5','SUBMITTED'),
                                   ('12','0','NOT SUBMITTED','ESS USER','1','SUBMITTED'),
                                   ('13','0','NOT SUBMITTED','ESS USER','5','NOT SUBMITTED'),
                                   ('14','0','NOT SUBMITTED','ESS USER','6','NOT SUBMITTED'),
                                   ('15','0','NOT SUBMITTED','ESS USER','0','NOT SUBMITTED'),
                                   ('16','0','NOT SUBMITTED','SUPERVISOR','0','NOT SUBMITTED'),
                                   ('17','0','NOT SUBMITTED','SUPERVISOR','5','NOT SUBMITTED'),
                                   ('18','0','NOT SUBMITTED','SUPERVISOR','1','SUBMITTED'),
                                   ('19','0','NOT SUBMITTED','ADMIN','0','NOT SUBMITTED'),
                                   ('20','0','NOT SUBMITTED','ADMIN','5','NOT SUBMITTED'),
                                   ('21','0','NOT SUBMITTED','ADMIN','1','SUBMITTED'),
                                   ('22','0','REJECTED','ESS USER','1','SUBMITTED'),
                                   ('23','0','REJECTED','ESS USER','0','REJECTED'),
                                   ('24','0','REJECTED','ESS USER','5','REJECTED'),
                                   ('25','0','REJECTED','SUPERVISOR','1','SUBMITTED'),
                                   ('26','0','REJECTED','SUPERVISOR','0','REJECTED'),
                                   ('27','0','REJECTED','SUPERVISOR','5','REJECTED'),
                                   ('28','0','REJECTED','ADMIN','0','REJECTED'),
                                   ('29','0','REJECTED','ADMIN','5','SUBMITTED'),
                                   ('30','0','REJECTED','ADMIN','1','SUBMITTED'),
                                   ('31','0','APPROVED','ESS USER','0','APPROVED'),
                                   ('32','0','APPROVED','SUPERVISOR','0','APPROVED'),
                                   ('33','0','APPROVED','ADMIN','0','APPROVED'),
                                   ('34','0','APPROVED','ADMIN','4','SUBMITTED'),
                                   ('35','1','PUNCHED IN','ESS USER','1','PUNCHED OUT'),
                                   ('36','1','INITIAL','ESS USER','0','PUNCHED IN'),
                                   ('37','2','INITIAL','ADMIN','1','APPLICATION INITIATED'),
                                   ('38','2','APPLICATION INITIATED','ADMIN','2','SHORTLISTED'),
                                   ('39','2','APPLICATION INITIATED','ADMIN','3','REJECTED'),
                                   ('40','2','SHORTLISTED','ADMIN','4','INTERVIEW SCHEDULED'),
                                   ('41','2','SHORTLISTED','ADMIN','3','REJECTED'),
                                   ('42','2','INTERVIEW SCHEDULED','ADMIN','3','REJECTED'),
                                   ('43','2','INTERVIEW SCHEDULED','ADMIN','5','INTERVIEW PASSED'),
                                   ('44','2','INTERVIEW SCHEDULED','ADMIN','6','INTERVIEW FAILED'),
                                   ('45','2','INTERVIEW PASSED','ADMIN','4','INTERVIEW SCHEDULED'),
                                   ('46','2','INTERVIEW PASSED','ADMIN','7','JOB OFFERED'),
                                   ('47','2','INTERVIEW PASSED','ADMIN','3','REJECTED'),
                                   ('48','2','INTERVIEW FAILED','ADMIN','3','REJECTED'),
                                   ('49','2','JOB OFFERED','ADMIN','8','OFFER DECLINED'),
                                   ('50','2','JOB OFFERED','ADMIN','3','REJECTED'),
                                   ('51','2','JOB OFFERED','ADMIN','9','HIRED'),
                                   ('52','2','OFFER DECLINED','ADMIN','3','REJECTED'),
                                   ('53','2','INITIAL','HIRING MANAGER','1','APPLICATION INITIATED'),
                                   ('54','2','APPLICATION INITIATED','HIRING MANAGER','2','SHORTLISTED'),
                                   ('55','2','APPLICATION INITIATED','HIRING MANAGER','3','REJECTED'),
                                   ('56','2','SHORTLISTED','HIRING MANAGER','4','INTERVIEW SCHEDULED'),
                                   ('57','2','SHORTLISTED','HIRING MANAGER','3','REJECTED'),
                                   ('58','2','INTERVIEW SCHEDULED','HIRING MANAGER','3','REJECTED'),
                                   ('59','2','INTERVIEW SCHEDULED','HIRING MANAGER','5','INTERVIEW PASSED'),
                                   ('60','2','INTERVIEW SCHEDULED','HIRING MANAGER','6','INTERVIEW FAILED'),
                                   ('61','2','INTERVIEW PASSED','HIRING MANAGER','4','INTERVIEW SCHEDULED'),
                                   ('62','2','INTERVIEW PASSED','HIRING MANAGER','7','JOB OFFERED'),
                                   ('63','2','INTERVIEW PASSED','HIRING MANAGER','3','REJECTED'),
                                   ('64','2','INTERVIEW FAILED','HIRING MANAGER','3','REJECTED'),
                                   ('65','2','JOB OFFERED','HIRING MANAGER','8','OFFER DECLINED'),
                                   ('66','2','JOB OFFERED','HIRING MANAGER','3','REJECTED'),
                                   ('67','2','JOB OFFERED','HIRING MANAGER','9','HIRED'),
                                   ('68','2','OFFER DECLINED','HIRING MANAGER','3','REJECTED'),
                                   ('69','2','INTERVIEW SCHEDULED','INTERVIEWER','5','INTERVIEW PASSED'),
                                   ('70','2','INTERVIEW SCHEDULED','INTERVIEWER','6','INTERVIEW FAILED'),
                                    ('71','1','INITIAL','ADMIN','5','PUNCHED IN'),
                                    ('72','1','PUNCHED IN','ADMIN','6','PUNCHED OUT'),
                                    ('73','1','PUNCHED IN','ADMIN','2','PUNCHED IN'),
                                    ('74','1','PUNCHED IN','ADMIN','7','N/A'),
                                    ('75','1','PUNCHED OUT','ADMIN','2','PUNCHED OUT'),
                                    ('76','1','PUNCHED OUT','ADMIN','3','PUNCHED OUT'),
                                    ('77','1','PUNCHED OUT','ADMIN','7','N/A'),
                                    ('78','0','INITIAL','ADMIN','7','NOT SUBMITTED'),
                                    ('79','0','INITIAL','ESS USER','7','NOT SUBMITTED'),
                                    ('80','0','INITIAL','SUPERVISOR','7','NOT SUBMITTED');
                                    
INSERT INTO `ohrm_report_group` VALUES (1,'timesheet', 'SELECT selectCondition FROM hs_hr_project_activity LEFT JOIN (SELECT * FROM ohrm_timesheet_item WHERE whereCondition1) AS ohrm_timesheet_item  ON (ohrm_timesheet_item.activity_id = hs_hr_project_activity.activity_id) LEFT JOIN hs_hr_project ON (hs_hr_project.project_id = hs_hr_project_activity.project_id) LEFT JOIN hs_hr_employee ON (hs_hr_employee.emp_number = ohrm_timesheet_item.employee_id) LEFT JOIN ohrm_timesheet ON (ohrm_timesheet.timesheet_id = ohrm_timesheet_item.timesheet_id) LEFT JOIN hs_hr_customer ON (hs_hr_customer.customer_id = hs_hr_project.customer_id) WHERE whereCondition2'),
                                       (2,'attendance', 'SELECT selectCondition FROM hs_hr_employee LEFT JOIN (SELECT * FROM ohrm_attendance_record WHERE ( ( ohrm_attendance_record.punch_in_user_time BETWEEN "#@fromDate@,@1970-01-01@#" AND #@"toDate"@,@CURDATE()@# ) AND ( ohrm_attendance_record.punch_out_user_time BETWEEN "#@fromDate@,@1970-01-01@#" AND #@"toDate"@,@CURDATE()@# ) ) ) AS ohrm_attendance_record ON (hs_hr_employee.emp_number = ohrm_attendance_record.employee_id) WHERE hs_hr_employee.emp_number = #@employeeId@,@hs_hr_employee.emp_number AND (hs_hr_employee.emp_status != "EST000" OR hs_hr_employee.emp_status is null) @# AND (hs_hr_employee.job_title_code = #@"jobTitle")@,@hs_hr_employee.job_title_code OR hs_hr_employee.job_title_code is null)@# AND (hs_hr_employee.work_station IN (#@subUnit)@,@SELECT id FROM hs_hr_compstructtree) OR hs_hr_employee.work_station is null@#) AND (hs_hr_employee.emp_status = #@"employeeStatus")@,@hs_hr_employee.emp_status OR hs_hr_employee.emp_status is null)@#');


INSERT INTO `ohrm_report` VALUES (1, 'Project Report', 1, 1),
                                 (2, 'Employee Report', 1, 1),
                                 (3, 'Project Activity Details', 1,1),
                                 (4, 'Attendance Total Summary Report', 2,0);

INSERT INTO `ohrm_filter_field` VALUES (1, 1, 'project_name', 'hs_hr_project.project_id', 'ohrmWidgetProjectList', 2, 'Runtime', 'true'),
                                       (2, 1, 'activity_show_deleted', 'hs_hr_project_activity.deleted', 'ohrmWidgetInputCheckbox', 2, 'Runtime', 'false'),
                                       (3, 1, 'project_date_range', 'date', 'ohrmWidgetDateRange', 1, 'Runtime', 'false'),
                                       (4, 1, 'employee', 'hs_hr_employee.emp_number', 'ohrmWidgetEmployeeListAutoFill', 2, 'Runtime', 'true'),
                                       (5, 1, 'activity_name', 'hs_hr_project_activity.activity_id', 'ohrmWidgetProjectActivityList', 2, 'Runtime', 'true'),
                                       (6, 1, 'project_name', 'hs_hr_project.project_id', 'ohrmWidgetProjectListWithAllOption', 2, 'Runtime', 'true'),
                                       (7, 1, 'only_inlclude_approved_timesheets', 'ohrm_timesheet.state', 'ohrmWidgetApprovedTimesheetInputCheckBox', 2, 'Runtime', null);

INSERT INTO `ohrm_display_field` VALUES (1, 'hs_hr_project.name', 'Project Name', 'projectname',  'false', null, null, 'label', '<xml><getter>projectname</getter></xml>', 200, '0', null, null),
                                        (2, 'hs_hr_project_activity.name', 'Activity Name', 'activityname', 'false', null, null, 'link', '<xml><labelGetter>activityname</labelGetter><placeholderGetters><id>activity_id</id><total>totalduration</total><projectId>projectId</projectId><from>fromDate</from><to>toDate</to><approved>onlyIncludeApprovedTimesheets</approved></placeholderGetters><urlPattern>../../displayProjectActivityDetailsReport?reportId=3#activityId={id}#total={total}#from={from}#to={to}#projectId={projectId}#onlyIncludeApprovedTimesheets={approved}</urlPattern></xml>', 200, '0', null, null),
                                        (3, 'hs_hr_project_activity.project_id', 'Project Id', null, 'false', null, null, 'label', '<xml><getter>project_id</getter></xml>', 75, '0', 'right', null),
                                        (4, 'hs_hr_project_activity.activity_id', 'Activity Id', null,  'false', null, null, 'label', '<xml><getter>activity_id</getter></xml>', 75, '0', 'right', null),
                                        (5, 'ohrm_timesheet_item.duration', 'Time (hours)', null, 'false', null, null, 'label', '<xml><getter>duration</getter></xml>', 75, '0', 'right', null),
                                        (6, 'hs_hr_employee.emp_firstname', 'Employee Firstname', null,  'false', null, null, 'label', '<xml><getter>emp_firstname</getter></xml>', 200, '0', null, null),
                                        (7, 'hs_hr_employee.emp_lastname', 'Employee Lastname', null, 'false', null, null, 'label', '<xml><getter>emp_lastname</getter></xml>', 200, '0', null, null),
                                        (8, 'hs_hr_project_activity.name', 'Activity Name', 'activityname', 'false', null, null, 'label', '<xml><getter>activityname</getter></xml>', 200, '0', null, null);

INSERT INTO `ohrm_group_field` VALUES (1, 'activity id', 'GROUP BY hs_hr_project_activity.activity_id', null),
                                      (2, 'employee number', 'GROUP BY hs_hr_employee.emp_number', null);

INSERT INTO `ohrm_selected_filter_field` VALUES (1, 1, 1, null, null, null),
                                                (1, 3, 2, null, null, null),
                                                (1, 7, 3, null, null, null),
                                                (2, 3, 4, null, null, null),
                                                (2, 4, 1, null, null, null),
                                                (2, 5, 3, null, null, null),
                                                (2, 6, 2, null, null, null),
                                                (2, 7, 5, null, null, null),
                                                (3, 3, 2, null, null, null),
                                                (3, 7, 3, null, null, null),
                                                (3, 5, 1, null, null, null);

INSERT INTO `ohrm_selected_display_field` VALUES (2, 2, 1),
                                                 (4, 8, 2);

INSERT INTO `ohrm_composite_display_field` VALUES (1, 'CONCAT(hs_hr_employee.emp_firstname, " " ,hs_hr_employee.emp_lastname)', 'Employee Name', 'employeeName', 'false', null, null, 'label', '<xml><getter>employeeName</getter></xml>', 300, '0', null, 'Deleted Employee'),
                                                  (2, 'CONCAT(hs_hr_customer.name, " - " ,hs_hr_project.name)', 'Project Name', 'projectname', 'false', null, null, 'label', '<xml><getter>projectname</getter></xml>', 300, '0', null, null);

INSERT INTO `ohrm_meta_display_field` VALUES (1, 3, 1),
                                             (2, 4, 1);

INSERT INTO `ohrm_selected_composite_display_field` VALUES (1, 1, 3),
                                                           (2, 1, 4),
                                                           (3, 2, 2);

INSERT INTO `ohrm_summary_display_field` VALUES (1, 'ROUND(COALESCE(sum(duration)/3600, 0),2)', 'Time (hours)', 'totalduration', 'false', null, null, 'label', '<xml><getter>totalduration</getter></xml>', 100, 'false', 'right', null),
                                                (2, 'ROUND(COALESCE(sum(TIMESTAMPDIFF(SECOND , ohrm_attendance_record.punch_in_utc_time , ohrm_attendance_record.punch_out_utc_time))/3600, 0),2)', 'Time (hours)', 'totalduration', 'false', null, null, 'label', '<xml><getter>totalduration</getter></xml>', 100, 'false', 'right', null);

INSERT INTO `ohrm_selected_group_field` VALUES (1, 1, 1),
                                               (1, 1, 2),
                                               (2, 1, 3),
                                               (2, 2, 4);
