<?php

/**
 * TimesheetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimesheetTable extends PluginTimesheetTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TimesheetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Timesheet');
    }
}