<?php

/**
 * BaseAuthProviderExtraDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $provider_id
 * @property integer $provider_type
 * @property string $client_id
 * @property string $client_secret
 * @property string $developer_key
 * @property OpenidProvider $OpenidProvider
 * 
 * @method integer                  getId()             Returns the current record's "id" value
 * @method integer                  getProviderId()     Returns the current record's "provider_id" value
 * @method integer                  getProviderType()   Returns the current record's "provider_type" value
 * @method string                   getClientId()       Returns the current record's "client_id" value
 * @method string                   getClientSecret()   Returns the current record's "client_secret" value
 * @method string                   getDeveloperKey()   Returns the current record's "developer_key" value
 * @method OpenidProvider           getOpenidProvider() Returns the current record's "OpenidProvider" value
 * @method AuthProviderExtraDetails setId()             Sets the current record's "id" value
 * @method AuthProviderExtraDetails setProviderId()     Sets the current record's "provider_id" value
 * @method AuthProviderExtraDetails setProviderType()   Sets the current record's "provider_type" value
 * @method AuthProviderExtraDetails setClientId()       Sets the current record's "client_id" value
 * @method AuthProviderExtraDetails setClientSecret()   Sets the current record's "client_secret" value
 * @method AuthProviderExtraDetails setDeveloperKey()   Sets the current record's "developer_key" value
 * @method AuthProviderExtraDetails setOpenidProvider() Sets the current record's "OpenidProvider" value
 * 
 * @package    orangehrm
 * @subpackage model\openidauthentication\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuthProviderExtraDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_auth_provider_extra_details');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('provider_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('provider_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('client_id', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('client_secret', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('developer_key', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OpenidProvider', array(
             'local' => 'provider_id',
             'foreign' => 'id'));
    }
}