<?php

/**
 * PluginEmployeeLanguage class file
 */

/**
 * PluginEmployeeLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\pim\plugin
 */
abstract class PluginEmployeeLanguage extends BaseEmployeeLanguage
{

}