<?php

/**
 * PluginMembershipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMembershipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMembershipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMembership');
    }
}