<?php

/**
 * PluginEmpEmergencyContact class file
 */

/**
 * PluginEmpEmergencyContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\pim\plugin
 */
abstract class PluginEmpEmergencyContact extends BaseEmpEmergencyContact
{

}