<?php

/**
 * PluginPerformanceTrackerReviewerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPerformanceTrackerReviewerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPerformanceTrackerReviewerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPerformanceTrackerReviewer');
    }
}