<?php

/**
 * PluginLeaveLeaveEntitlementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLeaveLeaveEntitlementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLeaveLeaveEntitlementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLeaveLeaveEntitlement');
    }
}