<?php

/**
 * PluginLeaveAdjustmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLeaveAdjustmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLeaveAdjustmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLeaveAdjustment');
    }
}