<?php

/**
 * PluginPayGradeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPayGradeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPayGradeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPayGrade');
    }
}