<?php

/**
 * AvailableGroupFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvailableGroupFieldTable extends PluginAvailableGroupFieldTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvailableGroupFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AvailableGroupField');
    }
}