<?php

/**
 * BaseWorkWeek
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $day
 * @property integer $length
 * 
 * @method integer  getDay()    Returns the current record's "day" value
 * @method integer  getLength() Returns the current record's "length" value
 * @method WorkWeek setDay()    Sets the current record's "day" value
 * @method WorkWeek setLength() Sets the current record's "length" value
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkWeek extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_weekends');
        $this->hasColumn('day', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('length', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}