<?php

/**
 * BaseUserSelectionRule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                $id                                 Type: integer(4), primary key
 * @property string             $name                               Type: string(255)
 * @property string             $description                        Type: string(255)
 * @property string             $implementation_class               Type: string(255)
 * @property string             $rule_xml_data                      Type: string
 *  
 * @method int                  getId()                             Type: integer(4), primary key
 * @method string               getName()                           Type: string(255)
 * @method string               getDescription()                    Type: string(255)
 * @method string               getImplementationClass()            Type: string(255)
 * @method string               getRuleXmlData()                    Type: string
 *  
 * @method UserSelectionRule    setId(int $val)                     Type: integer(4), primary key
 * @method UserSelectionRule    setName(string $val)                Type: string(255)
 * @method UserSelectionRule    setDescription(string $val)         Type: string(255)
 * @method UserSelectionRule    setImplementationClass(string $val) Type: string(255)
 * @method UserSelectionRule    setRuleXmlData(string $val)         Type: string
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserSelectionRule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_user_selection_rule');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('implementation_class', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('rule_xml_data', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}