<?php

/**
 * BaseSelectedDisplayFieldGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                        $id                                          Type: integer, primary key
 * @property int                        $report_id                                   Type: integer
 * @property int                        $display_field_group_id                      Type: int
 * @property Report                     $Report                                      
 * @property DisplayFieldGroup          $DisplayFieldGroup                           
 *  
 * @method int                          getId()                                      Type: integer, primary key
 * @method int                          getReportId()                                Type: integer
 * @method int                          getDisplayFieldGroupId()                     Type: int
 * @method Report                       getReport()                                  
 * @method DisplayFieldGroup            getDisplayFieldGroup()                       
 *  
 * @method SelectedDisplayFieldGroup    setId(int $val)                              Type: integer, primary key
 * @method SelectedDisplayFieldGroup    setReportId(int $val)                        Type: integer
 * @method SelectedDisplayFieldGroup    setDisplayFieldGroupId(int $val)             Type: int
 * @method SelectedDisplayFieldGroup    setReport(Report $val)                       
 * @method SelectedDisplayFieldGroup    setDisplayFieldGroup(DisplayFieldGroup $val) 
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSelectedDisplayFieldGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_selected_display_field_group');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             ));
        $this->hasColumn('report_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('display_field_group_id', 'int', null, array(
             'type' => 'int',
             'unsigned' => true,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Report', array(
             'local' => 'report_id',
             'foreign' => 'reportId',
             'onDelete' => 'cascade'));

        $this->hasOne('DisplayFieldGroup', array(
             'local' => 'display_field_group_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}