<?php

/**
 * BaseConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string  $key                  Type: string(100), primary key
 * @property string  $value                Type: string(60000)
 *  
 * @method string    getKey()              Type: string(100), primary key
 * @method string    getValue()            Type: string(60000)
 *  
 * @method Config    setKey(string $val)   Type: string(100), primary key
 * @method Config    setValue(string $val) Type: string(60000)
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_config');
        $this->hasColumn('`key` as key', 'string', 100, array(
             'type' => 'string',
             'primary' => true,
             'length' => 100,
             ));
        $this->hasColumn('value', 'string', 60000, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => 60000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}