<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePerformanceReview extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_performance_review');
        $this->hasColumn('id as id', 'integer', 13, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('employee_id as employeeId', 'integer', 13, array(
             'type' => 'integer',
             'length' => '13',
             ));
        $this->hasColumn('reviewer_id as reviewerId', 'integer', 13, array(
             'type' => 'integer',
             'length' => '13',
             ));
        $this->hasColumn('creator_id as creatorId', 'string', 36, array(
             'type' => 'string',
             'length' => '36',
             ));
        $this->hasColumn('job_title_code as jobTitleCode', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('sub_division_id as subDivisionId', 'integer', 13, array(
             'type' => 'integer',
             'length' => '13',
             ));
        $this->hasColumn('creation_date as creationDate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('period_from as periodFrom', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('period_to as periodTo', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('due_date as dueDate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('state as state', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('kpis as kpis', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'employeeId',
             'foreign' => 'emp_number'));

        $this->hasOne('Employee as Reviewer', array(
             'local' => 'reviewerId',
             'foreign' => 'emp_number'));

        $this->hasOne('Users as Creator', array(
             'local' => 'creatorId',
             'foreign' => 'id'));

        $this->hasMany('PerformanceReviewComment', array(
             'local' => 'id',
             'foreign' => 'pr_id'));

        $this->hasOne('JobTitle', array(
             'local' => 'jobTitleCode',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as SubDivision', array(
             'local' => 'subDivisionId',
             'foreign' => 'id'));
    }
}