<?php

/**
 * BaseEmpDependents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emp_number
 * @property decimal $seqno
 * @property string $name
 * @property string $relationship
 * @property Employee $Employee
 * 
 * @method integer       getEmpNumber()    Returns the current record's "emp_number" value
 * @method decimal       getSeqno()        Returns the current record's "seqno" value
 * @method string        getName()         Returns the current record's "name" value
 * @method string        getRelationship() Returns the current record's "relationship" value
 * @method Employee      getEmployee()     Returns the current record's "Employee" value
 * @method EmpDependents setEmpNumber()    Sets the current record's "emp_number" value
 * @method EmpDependents setSeqno()        Sets the current record's "seqno" value
 * @method EmpDependents setName()         Sets the current record's "name" value
 * @method EmpDependents setRelationship() Sets the current record's "relationship" value
 * @method EmpDependents setEmployee()     Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpDependents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_dependents');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('ed_seqno as seqno', 'decimal', 2, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('ed_name as name', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('ed_relationship as relationship', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}