<?php

/**
 * BaseSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $skill_code
 * @property string $skill_name
 * @property string $skill_description
 * @property Doctrine_Collection $EmployeeSkill
 * 
 * @method string              getSkillCode()         Returns the current record's "skill_code" value
 * @method string              getSkillName()         Returns the current record's "skill_name" value
 * @method string              getSkillDescription()  Returns the current record's "skill_description" value
 * @method Doctrine_Collection getEmployeeSkill()     Returns the current record's "EmployeeSkill" collection
 * @method Skill               setSkillCode()         Sets the current record's "skill_code" value
 * @method Skill               setSkillName()         Sets the current record's "skill_name" value
 * @method Skill               setSkillDescription()  Sets the current record's "skill_description" value
 * @method Skill               setEmployeeSkill()     Sets the current record's "EmployeeSkill" collection
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSkill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_skill');
        $this->hasColumn('skill_code', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => 13,
             ));
        $this->hasColumn('skill_name', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('skill_description', 'string', 2147483647, array(
             'type' => 'string',
             'length' => 2147483647,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EmployeeSkill', array(
             'local' => 'skill_code',
             'foreign' => 'skill_code'));
    }
}