<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_language');
        $this->hasColumn('lang_code', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('lang_name', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
    }

    public function setUp()
    {
        $this->hasMany('EmployeeLanguage', array(
             'local' => 'lang_code',
             'foreign' => 'lang_code'));
    }
}