<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePerformanceReviewComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_performance_review_comments');
        $this->hasColumn('id as id', 'integer', 13, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '13',
             ));
        $this->hasColumn('pr_id as performanceReviewId', 'integer', 13, array(
             'type' => 'integer',
             'length' => '13',
             ));
        $this->hasColumn('employee_id as employeeId', 'integer', 13, array(
             'type' => 'integer',
             'length' => '13',
             ));
        $this->hasColumn('comment as comment', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('create_date as createDate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'employeeId',
             'foreign' => 'emp_number'));

        $this->hasOne('PerformanceReview', array(
             'local' => 'pr_id',
             'foreign' => 'id'));
    }
}