<?php

/**
 * BaseProjectActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activity_id
 * @property integer $project_id
 * @property integer $deleted
 * @property string $name
 * @property Project $Project
 * 
 * @method integer         getActivityId()  Returns the current record's "activity_id" value
 * @method integer         getProjectId()   Returns the current record's "project_id" value
 * @method integer         getDeleted()     Returns the current record's "deleted" value
 * @method string          getName()        Returns the current record's "name" value
 * @method Project         getProject()     Returns the current record's "Project" value
 * @method ProjectActivity setActivityId()  Sets the current record's "activity_id" value
 * @method ProjectActivity setProjectId()   Sets the current record's "project_id" value
 * @method ProjectActivity setDeleted()     Sets the current record's "deleted" value
 * @method ProjectActivity setName()        Sets the current record's "name" value
 * @method ProjectActivity setProject()     Sets the current record's "Project" value
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_project_activity');
        $this->hasColumn('activity_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('project_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('deleted', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 1,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'project_id'));
    }
}