<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayperiod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_payperiod');
        $this->hasColumn('payperiod_code as code', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('payperiod_name as name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('EmpBasicsalary', array(
             'local' => 'payperiod_code',
             'foreign' => 'payperiod_code'));
    }
}